"""
Renders the self-contained HTML dashboard from a data dict.

The output is a single HTML file with:
- Inline CSS (dark theme)
- Inline JS (tab switching, sorting, expand/collapse)
- Inline SVG charts (generated by svg_charts.py)
- Embedded JSON data blob
"""

from __future__ import annotations

import html
import json
from typing import Any

from . import svg_charts as sc

# ── CSS ───────────────────────────────────────────────────────────────

_CSS = """\
*{box-sizing:border-box;margin:0;padding:0}
body{background:#1a1a2e;color:#e0e0e0;font-family:ui-monospace,SFMono-Regular,
"SF Mono",Menlo,Consolas,monospace;font-size:13px;line-height:1.5;padding:0}
a{color:#53d8fb;text-decoration:none}
.wrap{max-width:1400px;margin:0 auto;padding:16px 20px}

/* Header */
.hdr{display:flex;align-items:center;gap:20px;padding:12px 20px;
background:#0f3460;border-bottom:1px solid #16213e}
.hdr h1{font-size:16px;font-weight:600;white-space:nowrap}
.hdr .meta{font-size:11px;color:#8899aa;margin-left:auto;white-space:nowrap}
.pills{display:flex;gap:10px;flex-wrap:wrap}
.pill{display:inline-flex;flex-direction:column;align-items:center;
padding:6px 14px;border:1px solid #53d8fb;border-radius:8px;min-width:80px}
.pill-val{font-size:18px;font-weight:700}
.pill-label{font-size:10px;color:#8899aa;text-transform:uppercase;letter-spacing:0.5px}

/* Tabs */
.tabs{display:flex;gap:0;border-bottom:2px solid #16213e;margin-top:12px}
.tab{padding:8px 18px;cursor:pointer;color:#8899aa;border-bottom:2px solid transparent;
margin-bottom:-2px;font-size:13px;transition:color .15s}
.tab:hover{color:#e0e0e0}
.tab.active{color:#53d8fb;border-bottom-color:#53d8fb}
.tab-content{display:none;padding:16px 0}
.tab-content.active{display:block}

/* Cards */
.card{background:#16213e;border-radius:8px;padding:16px;margin-bottom:14px}
.card h3{font-size:14px;color:#53d8fb;margin-bottom:10px}
.card-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:12px}

/* Tables */
table{width:100%;border-collapse:collapse;font-size:12px}
th{text-align:left;padding:8px 10px;color:#8899aa;border-bottom:1px solid #0f3460;
cursor:pointer;user-select:none;white-space:nowrap}
th:hover{color:#53d8fb}
td{padding:7px 10px;border-bottom:1px solid rgba(15,52,96,.4)}
tr:hover td{background:rgba(83,216,251,.04)}
.num{text-align:right;font-variant-numeric:tabular-nums}

/* Status */
.st-healthy{color:#00b894}.st-degraded{color:#fdcb6e}.st-unhealthy{color:#ff6b6b}
.st-pass{color:#00b894}.st-fail{color:#ff6b6b}

/* Recommendations */
.recs{background:rgba(253,203,110,.08);border:1px solid rgba(253,203,110,.25);
border-radius:6px;padding:10px 14px;margin-bottom:14px;font-size:12px}
.recs li{list-style:none;padding:3px 0}
.recs li::before{content:"!";display:inline-block;width:18px;height:18px;
line-height:18px;text-align:center;background:#fdcb6e;color:#1a1a2e;
border-radius:50%;font-size:10px;font-weight:700;margin-right:8px}

/* Event stream */
.events-toggle{cursor:pointer;padding:10px 0;color:#53d8fb;font-size:13px}
.events-body{display:none;max-height:400px;overflow-y:auto}
.events-body.open{display:block}
.evt-type{display:inline-block;padding:1px 6px;border-radius:3px;font-size:10px;
background:rgba(83,216,251,.15);color:#53d8fb}

/* Responsive */
@media(max-width:900px){.card-grid{grid-template-columns:1fr}
.pills{gap:6px}.pill{min-width:60px;padding:4px 8px}}

/* Utility */
.flex{display:flex;gap:16px;align-items:flex-start;flex-wrap:wrap}
.grow{flex:1 1 0;min-width:0}
.text-dim{color:#8899aa}
.text-green{color:#00b894}
.text-yellow{color:#fdcb6e}
.text-red{color:#ff6b6b}
.mt{margin-top:12px}
.mb{margin-bottom:12px}
"""

# ── JS ────────────────────────────────────────────────────────────────

_JS = """\
document.addEventListener('DOMContentLoaded',function(){
  // Tab switching
  document.querySelectorAll('.tab').forEach(function(tab){
    tab.addEventListener('click',function(){
      document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));
      document.querySelectorAll('.tab-content').forEach(c=>c.classList.remove('active'));
      tab.classList.add('active');
      document.getElementById('tab-'+tab.dataset.tab).classList.add('active');
    });
  });

  // Table sorting
  document.querySelectorAll('th[data-sort]').forEach(function(th){
    th.addEventListener('click',function(){
      var table=th.closest('table'),tbody=table.querySelector('tbody');
      if(!tbody)return;
      var idx=Array.from(th.parentNode.children).indexOf(th);
      var rows=Array.from(tbody.querySelectorAll('tr'));
      var asc=th.dataset.dir!=='asc';th.dataset.dir=asc?'asc':'desc';
      rows.sort(function(a,b){
        var av=a.children[idx].textContent.trim();
        var bv=b.children[idx].textContent.trim();
        var an=parseFloat(av.replace(/[^\\d.-]/g,''));
        var bn=parseFloat(bv.replace(/[^\\d.-]/g,''));
        if(!isNaN(an)&&!isNaN(bn))return asc?an-bn:bn-an;
        return asc?av.localeCompare(bv):bv.localeCompare(av);
      });
      rows.forEach(function(r){tbody.appendChild(r)});
    });
  });

  // Event stream toggle
  var toggle=document.getElementById('events-toggle');
  if(toggle){toggle.addEventListener('click',function(){
    var body=document.getElementById('events-body');
    body.classList.toggle('open');
    toggle.textContent=body.classList.contains('open')?
      '▼ Event Stream (click to collapse)':'▶ Event Stream (click to expand)';
  });}
});
"""


# ── Renderer ──────────────────────────────────────────────────────────

class HTMLRenderer:
    """Assembles the final HTML page from collected data."""

    def render(self, data: dict[str, Any]) -> str:
        meta = data.get("meta", {})
        parts = [
            "<!DOCTYPE html><html lang='en'><head>",
            "<meta charset='utf-8'>",
            "<meta name='viewport' content='width=device-width,initial-scale=1'>",
            f"<title>TappsCodingAgents Dashboard - {_esc(meta.get('project_name', ''))}</title>",
            f"<style>{_CSS}</style>",
            "</head><body>",
            self._render_header(data),
            '<div class="wrap">',
            self._render_tabs(),
            self._render_agents_tab(data),
            self._render_experts_tab(data),
            self._render_cache_tab(data),
            self._render_quality_tab(data),
            self._render_workflows_tab(data),
            self._render_learning_tab(data),
            self._render_health_tab(data),
            self._render_events(data),
            "</div>",
            f'<script id="dashboard-data" type="application/json">{json.dumps(data, default=str)}</script>',
            f"<script>{_JS}</script>",
            "</body></html>",
        ]
        return "\n".join(parts)

    # ── header ────────────────────────────────────────────────────────

    def _render_header(self, data: dict) -> str:
        meta = data.get("meta", {})
        health = data.get("health", {})
        agents = data.get("agents", {}).get("summary", {})
        cache = data.get("cache", {}).get("summary", {})
        experts = data.get("experts", {}).get("summary", {})
        workflows = data.get("workflows", {}).get("summary", {})

        gauge = sc.ring_gauge(health.get("overall_score", 0), label="Health")

        pills = "".join([
            sc.number_pill(str(workflows.get("total", 0)), "Workflows"),
            sc.number_pill(f"{workflows.get('success_rate', 0):.0f}%", "Success 30d",
                           colour=sc.GREEN if workflows.get("success_rate", 0) >= 80 else sc.YELLOW),
            sc.number_pill(f"{cache.get('hit_rate', 0):.0f}%", "Cache Hit",
                           colour=sc.GREEN if cache.get("hit_rate", 0) >= 60 else sc.YELLOW),
            sc.number_pill(str(experts.get("active", 0)), "Experts"),
            sc.number_pill(str(agents.get("active", 0)), "Active Agents"),
        ])

        ts = meta.get("generated_at", "")[:19].replace("T", " ")
        return (
            f'<div class="hdr">{gauge}'
            f'<div><h1>TappsCodingAgents Dashboard</h1>'
            f'<div class="pills">{pills}</div></div>'
            f'<div class="meta">{_esc(meta.get("project_name", ""))}<br>{ts}<br>'
            f'v{_esc(meta.get("tapps_agents_version", ""))}</div></div>'
        )

    # ── tab bar ───────────────────────────────────────────────────────

    def _render_tabs(self) -> str:
        tabs = [
            ("agents", "Agents"),
            ("experts", "Experts"),
            ("cache", "Cache & RAG"),
            ("quality", "Quality"),
            ("workflows", "Workflows"),
            ("learning", "Learning"),
            ("health", "Health"),
        ]
        items = "".join(
            f'<div class="tab{" active" if i == 0 else ""}" data-tab="{tid}">{label}</div>'
            for i, (tid, label) in enumerate(tabs)
        )
        return f'<div class="tabs">{items}</div>'

    # ── agents tab ────────────────────────────────────────────────────

    def _render_agents_tab(self, data: dict) -> str:
        agents = data.get("agents", {}).get("agents", [])
        recs = [r for r in data.get("recommendations", []) if r.get("tab") == "agents"]
        rec_html = self._render_recs(recs)

        rows = ""
        for a in sorted(agents, key=lambda x: x.get("executions", 0), reverse=True):
            rate = a.get("success_rate", 0)
            rate_cls = "text-green" if rate >= 80 else ("text-yellow" if rate >= 60 else "text-red")
            dur = a.get("avg_duration_ms", 0)
            dur_str = f"{dur / 1000:.1f}s" if dur >= 1000 else f"{dur:.0f}ms"
            trend = sc.sparkline(a.get("trend", []), width=80, height=20)
            last = _short_time(a.get("last_run", ""))
            rows += (
                f"<tr><td>{_esc(a.get('name', ''))}</td>"
                f'<td class="num">{a.get("executions", 0)}</td>'
                f'<td class="num {rate_cls}">{rate:.1f}%</td>'
                f'<td class="num">{dur_str}</td>'
                f"<td>{last}</td>"
                f"<td>{trend}</td></tr>"
            )

        worst = [a for a in agents if 0 < a.get("success_rate", 100) < 80]
        unused = [a for a in agents if a.get("executions", 0) == 0]
        callouts = ""
        if worst:
            items = ", ".join(f'{a["name"]} ({a["success_rate"]:.0f}%)' for a in worst)
            callouts += f'<div class="card"><h3>Worst Performers</h3><p>{items}</p></div>'
        if unused:
            names = ", ".join(a["name"] for a in unused)
            callouts += f'<div class="card"><h3>Unused Agents</h3><p class="text-dim">{names}</p></div>'

        return (
            f'<div id="tab-agents" class="tab-content active">'
            f"{rec_html}"
            f'<div class="card"><h3>Agent Performance</h3>'
            f"<table><thead><tr>"
            f'<th data-sort>Agent</th><th data-sort>Executions</th>'
            f'<th data-sort>Success %</th><th data-sort>Avg Duration</th>'
            f"<th data-sort>Last Run</th><th>Trend</th>"
            f"</tr></thead><tbody>{rows}</tbody></table></div>"
            f"{callouts}</div>"
        )

    # ── experts tab ───────────────────────────────────────────────────

    def _render_experts_tab(self, data: dict) -> str:
        experts_data = data.get("experts", {})
        experts = experts_data.get("experts", [])
        dist = experts_data.get("confidence_distribution", {})
        roi = experts_data.get("roi", {})
        reason_dist = experts_data.get("selection_reason_distribution", {})
        recent = experts_data.get("recent_consultations", [])
        recs = [r for r in data.get("recommendations", []) if r.get("tab") == "experts"]

        rows = ""
        for e in sorted(experts, key=lambda x: x.get("consultations", 0), reverse=True):
            conf = e.get("avg_confidence", 0)
            conf_cls = "text-green" if conf >= 0.7 else ("text-yellow" if conf >= 0.5 else "text-red")
            domains = ", ".join(e.get("domains", [])[:3])
            rows += (
                f"<tr><td>{_esc(e.get('id', ''))}</td>"
                f'<td class="num">{e.get("consultations", 0)}</td>'
                f'<td class="num {conf_cls}">{conf:.2f}</td>'
                f'<td class="num">{e.get("first_pass_rate", 0):.1f}%</td>'
                f'<td class="num">{e.get("quality_impact", 0):+.1f}</td>'
                f"<td class=\"text-dim\">{_esc(domains)}</td></tr>"
            )

        # Confidence distribution bar
        dist_chart = sc.horizontal_bar_chart(
            labels=["Very High (0.85+)", "High (0.7-0.85)", "Medium (0.5-0.7)", "Low (<0.5)"],
            values=[dist.get("very_high", 0), dist.get("high", 0), dist.get("medium", 0), dist.get("low", 0)],
            colours=[sc.GREEN, sc.CYAN, sc.YELLOW, sc.RED],
            width=320,
        )

        roi_html = (
            f'<div class="card"><h3>Expert ROI</h3>'
            f'<p>Time saved: <b>{roi.get("time_saved_hours", 0):.1f}h</b> &nbsp; '
            f'Bugs prevented: <b>{roi.get("bugs_prevented", 0)}</b> &nbsp; '
            f'ROI: <b>{roi.get("roi_percentage", 0):.0f}%</b></p></div>'
        )

        # Selection reason distribution (table)
        reason_order = ["weight_matrix", "domain_match_builtin", "domain_match_customer", "fallback_builtin", "fallback_all"]
        reason_rows = ""
        for r in reason_order:
            cnt = reason_dist.get(r, 0)
            if cnt > 0 or r in reason_dist:
                reason_rows += f"<tr><td class=\"text-dim\">{_esc(r)}</td><td class=\"num\">{cnt}</td></tr>"
        for r, cnt in sorted(reason_dist.items(), key=lambda x: -x[1]):
            if r not in reason_order:
                reason_rows += f"<tr><td class=\"text-dim\">{_esc(r)}</td><td class=\"num\">{cnt}</td></tr>"
        selection_section = (
            f'<div class="card"><h3>Selection Reason Distribution</h3>'
            f'<table><thead><tr><th>Reason</th><th>Count</th></tr></thead><tbody>{reason_rows or "<tr><td class=\"text-dim\">No data yet</td><td>0</td></tr>"}</tbody></table></div>'
        )

        # Recent consultations (last 20)
        recent_rows = ""
        for c in recent[:20]:
            ts = c.get("timestamp", "")[:19] if c.get("timestamp") else ""
            expert_ids = c.get("expert_ids", [])
            experts_str = ", ".join(expert_ids[:3]) + ("..." if len(expert_ids) > 3 else "")
            recent_rows += (
                f"<tr><td class=\"text-dim\">{_esc(ts)}</td>"
                f"<td>{_esc(c.get('agent_id', ''))}</td>"
                f"<td>{_esc(c.get('domain', ''))}</td>"
                f"<td class=\"text-dim\">{_esc(experts_str)}</td>"
                f"<td>{_esc(c.get('selection_reason', 'unknown'))}</td></tr>"
            )
        recent_section = (
            f'<div class="card"><h3>Recent Consultations</h3>'
            f'<table><thead><tr><th>Timestamp</th><th>Agent</th><th>Domain</th><th>Experts</th><th>Selection Reason</th></tr></thead>'
            f'<tbody>{recent_rows or "<tr><td colspan=\"5\" class=\"text-dim\">No consultations yet</td></tr>"}</tbody></table></div>'
        )

        return (
            f'<div id="tab-experts" class="tab-content">'
            f"{self._render_recs(recs)}"
            f'<div class="flex">'
            f'<div class="grow"><div class="card"><h3>Expert Leaderboard</h3>'
            f"<table><thead><tr>"
            f'<th data-sort>Expert</th><th data-sort>Consultations</th>'
            f'<th data-sort>Avg Confidence</th><th data-sort>First-Pass %</th>'
            f'<th data-sort>Quality Impact</th><th>Domains</th>'
            f"</tr></thead><tbody>{rows}</tbody></table></div></div>"
            f'<div style="min-width:340px"><div class="card">'
            f"<h3>Confidence Distribution</h3>{dist_chart}</div>"
            f"{roi_html}</div></div>"
            f'<div class="flex" style="margin-top:16px">'
            f'<div class="grow">{selection_section}</div>'
            f'<div class="grow">{recent_section}</div></div>'
            f"</div>"
        )

    # ── cache tab ─────────────────────────────────────────────────────

    def _render_cache_tab(self, data: dict) -> str:
        cache = data.get("cache", {})
        summary = cache.get("summary", {})
        libraries = cache.get("libraries", [])
        recs = [r for r in data.get("recommendations", []) if r.get("tab") == "cache"]

        gauge = sc.ring_gauge(summary.get("hit_rate", 0), label="Hit Rate", size=100, stroke=8)

        stats = (
            f'<div class="flex" style="gap:24px;align-items:center">'
            f"{gauge}"
            f'<div><p>Entries: <b>{summary.get("total_entries", 0)}</b> &nbsp; '
            f'Tokens: <b>{summary.get("total_tokens", 0):,}</b> &nbsp; '
            f'Size: <b>{summary.get("total_size_bytes", 0) / 1024:.0f} KB</b></p>'
            f'<p class="text-dim">RAG Quality: {cache.get("rag_quality_score", 0):.1f}</p></div></div>'
        )

        rows = ""
        for lib in sorted(libraries, key=lambda x: x.get("hits", 0), reverse=True):
            size_kb = lib.get("size_bytes", 0) / 1024
            rows += (
                f"<tr><td>{_esc(lib.get('name', ''))}</td>"
                f'<td class="num">{lib.get("topics", 0)}</td>'
                f'<td class="num">{lib.get("hits", 0)}</td>'
                f'<td class="num">{lib.get("tokens", 0):,}</td>'
                f'<td class="num">{size_kb:.0f} KB</td>'
                f"<td class=\"text-dim\">{_short_time(lib.get('last_accessed', ''))}</td></tr>"
            )

        return (
            f'<div id="tab-cache" class="tab-content">'
            f"{self._render_recs(recs)}"
            f'<div class="card"><h3>Cache Overview</h3>{stats}</div>'
            f'<div class="card"><h3>Library Breakdown</h3>'
            f"<table><thead><tr>"
            f'<th data-sort>Library</th><th data-sort>Topics</th>'
            f'<th data-sort>Hits</th><th data-sort>Tokens</th>'
            f"<th data-sort>Size</th><th data-sort>Last Access</th>"
            f"</tr></thead><tbody>{rows}</tbody></table></div></div>"
        )

    # ── quality tab ───────────────────────────────────────────────────

    def _render_quality_tab(self, data: dict) -> str:
        quality = data.get("quality", {})
        dims = quality.get("dimensions", {})
        failures = quality.get("recent_failures", [])
        recs = [r for r in data.get("recommendations", []) if r.get("tab") == "quality"]

        gauge = sc.ring_gauge(quality.get("gate_pass_rate", 0), label="Pass Rate", size=100, stroke=8)

        # Radar chart for dimensions (only if we have data)
        radar = ""
        if any(v > 0 for v in dims.values()):
            radar = sc.radar_chart(dims, max_val=100, size=240)

        fail_rows = ""
        for f in failures[:15]:
            fail_rows += (
                f"<tr><td>{_esc(f.get('workflow', ''))}</td>"
                f"<td>{_esc(f.get('step', ''))}</td>"
                f"<td>{_esc(f.get('skill', ''))}</td>"
                f"<td class=\"text-dim\">{_short_time(f.get('date', ''))}</td>"
                f"<td class=\"text-red\">{_esc(f.get('error', ''))}</td></tr>"
            )

        return (
            f'<div id="tab-quality" class="tab-content">'
            f"{self._render_recs(recs)}"
            f'<div class="flex">'
            f'<div class="card" style="min-width:120px">'
            f"<h3>Gate Pass Rate</h3>{gauge}"
            f'<p class="mt text-dim">Avg Score: {quality.get("avg_score", 0):.1f}</p></div>'
            f'<div class="card grow"><h3>Quality Dimensions</h3>'
            + (radar if radar else '<p class="text-dim">No dimension data yet</p>')
            + "</div></div>"
            + (
                f'<div class="card"><h3>Recent Failures</h3>'
                f"<table><thead><tr>"
                f"<th>Workflow</th><th>Step</th><th>Skill</th><th>Date</th><th>Error</th>"
                f"</tr></thead><tbody>{fail_rows}</tbody></table></div>"
                if failures
                else ""
            )
            + "</div>"
        )

    # ── workflows tab ─────────────────────────────────────────────────

    def _render_workflows_tab(self, data: dict) -> str:
        wf_data = data.get("workflows", {})
        workflows = wf_data.get("workflows", [])
        epics = wf_data.get("epics", [])
        recs = [r for r in data.get("recommendations", []) if r.get("tab") == "workflows"]

        rows = ""
        for w in sorted(workflows, key=lambda x: x.get("executions", 0), reverse=True):
            rate = w.get("success_rate", 0)
            rate_cls = "text-green" if rate >= 80 else ("text-yellow" if rate >= 60 else "text-red")
            dur = w.get("avg_duration_ms", 0)
            dur_str = f"{dur / 1000:.1f}s" if dur >= 1000 else f"{dur:.0f}ms"
            rows += (
                f"<tr><td>{_esc(w.get('name', ''))}</td>"
                f'<td class="num">{w.get("executions", 0)}</td>'
                f'<td class="num {rate_cls}">{rate:.1f}%</td>'
                f'<td class="num">{dur_str}</td>'
                f'<td class="num">{w.get("avg_steps", 0):.1f}</td>'
                f"<td class=\"text-dim\">{_short_time(w.get('last_run', ''))}</td></tr>"
            )

        epic_cards = ""
        for ep in epics:
            total = ep.get("stories_total", 0) or 1
            done = ep.get("stories_done", 0)
            pct = done / total * 100
            bar_w = min(pct, 100)
            epic_cards += (
                f'<div class="card"><h3>{_esc(ep.get("title", ep.get("id", "")))}</h3>'
                f'<p>{done}/{total} stories ({pct:.0f}%)</p>'
                f'<div style="background:#0f3460;height:6px;border-radius:3px;margin-top:6px">'
                f'<div style="background:#53d8fb;height:6px;border-radius:3px;width:{bar_w:.0f}%"></div>'
                f"</div></div>"
            )

        return (
            f'<div id="tab-workflows" class="tab-content">'
            f"{self._render_recs(recs)}"
            f'<div class="card"><h3>Workflow Performance</h3>'
            f"<table><thead><tr>"
            f'<th data-sort>Workflow</th><th data-sort>Executions</th>'
            f'<th data-sort>Success %</th><th data-sort>Avg Duration</th>'
            f'<th data-sort>Avg Steps</th><th data-sort>Last Run</th>'
            f"</tr></thead><tbody>{rows}</tbody></table></div>"
            + (f'<h3 class="mt mb" style="color:#53d8fb">Epics</h3>'
               f'<div class="card-grid">{epic_cards}</div>' if epic_cards else "")
            + "</div>"
        )

    # ── learning tab ──────────────────────────────────────────────────

    def _render_learning_tab(self, data: dict) -> str:
        learning = data.get("learning", {})
        first_pass = learning.get("first_pass_trend", [])
        adjustments = learning.get("weight_adjustments", [])
        recs = [r for r in data.get("recommendations", []) if r.get("tab") == "learning"]

        trend_chart = ""
        if first_pass:
            values = [fp.get("rate", 0) for fp in first_pass[-30:]]
            trend_chart = sc.sparkline(values, width=400, height=60, colour=sc.GREEN)

        adj_rows = ""
        for adj in adjustments[:20]:
            adj_rows += (
                f"<tr><td>{_esc(adj.get('expert', ''))}</td>"
                f'<td class="num">{adj.get("old_weight", 0):.3f}</td>'
                f'<td class="num">{adj.get("new_weight", 0):.3f}</td>'
                f"<td class=\"text-dim\">{_esc(adj.get('reason', ''))}</td>"
                f"<td class=\"text-dim\">{_short_time(adj.get('date', ''))}</td></tr>"
            )

        return (
            f'<div id="tab-learning" class="tab-content">'
            f"{self._render_recs(recs)}"
            f'<div class="card"><h3>First-Pass Success Rate Trend</h3>'
            + (trend_chart if trend_chart else '<p class="text-dim">No learning data yet</p>')
            + "</div>"
            + (
                f'<div class="card"><h3>Expert Weight Adjustments</h3>'
                f"<table><thead><tr>"
                f"<th>Expert</th><th>Old Weight</th><th>New Weight</th>"
                f"<th>Reason</th><th>Date</th>"
                f"</tr></thead><tbody>{adj_rows}</tbody></table></div>"
                if adj_rows
                else ""
            )
            + "</div>"
        )

    # ── health tab ────────────────────────────────────────────────────

    def _render_health_tab(self, data: dict) -> str:
        health = data.get("health", {})
        checks = health.get("checks", [])
        recs = [r for r in data.get("recommendations", []) if r.get("tab") == "health"]

        cards = ""
        for ck in checks:
            status = ck.get("status", "unknown")
            status_cls = f"st-{status}"
            badge = sc.status_badge(status)
            score = ck.get("score", 0)
            remediation = ck.get("remediation", [])
            rem_html = ""
            if remediation:
                items = "".join(f"<li>{_esc(r)}</li>" for r in remediation[:3])
                rem_html = f'<ul class="mt" style="font-size:11px;padding-left:16px">{items}</ul>'

            details = ck.get("details", {})
            detail_items = "".join(
                f'<span class="text-dim">{_esc(str(k))}: {_esc(str(v))}</span><br>'
                for k, v in list(details.items())[:5]
            )

            cards += (
                f'<div class="card">'
                f'<h3>{badge} {_esc(ck.get("name", ""))}'
                f' <span class="{status_cls}" style="font-size:11px">({status})</span></h3>'
                f'<p>Score: <b>{score:.0f}</b></p>'
                f'{f"<div class=mt>{detail_items}</div>" if detail_items else ""}'
                f"{rem_html}</div>"
            )

        return (
            f'<div id="tab-health" class="tab-content">'
            f"{self._render_recs(recs)}"
            f'<div class="card"><h3>Overall Health</h3>'
            f'{sc.ring_gauge(health.get("overall_score", 0), label="Overall", size=100, stroke=8)}</div>'
            f'<div class="card-grid">{cards}</div></div>'
        )

    # ── events ────────────────────────────────────────────────────────

    def _render_events(self, data: dict) -> str:
        events = data.get("events", [])
        if not events:
            return (
                '<div class="events-toggle" id="events-toggle">'
                "Event Stream (no events)</div>"
            )

        rows = ""
        for evt in events[:100]:
            rows += (
                f"<tr><td class=\"text-dim\">{_short_time(evt.get('timestamp', ''))}</td>"
                f'<td><span class="evt-type">{_esc(evt.get("event_type", ""))}</span></td>'
                f"<td>{_esc(evt.get('workflow_id', ''))}</td>"
                f"<td>{_esc(evt.get('step_id', ''))}</td>"
                f"<td>{_esc(evt.get('status', ''))}</td>"
                f"<td class=\"text-dim\">{_esc(evt.get('details', '')[:80])}</td></tr>"
            )

        return (
            '<div class="events-toggle" id="events-toggle">'
            "Event Stream (click to expand)</div>"
            '<div class="events-body" id="events-body">'
            "<table><thead><tr>"
            "<th>Time</th><th>Type</th><th>Workflow</th>"
            "<th>Step</th><th>Status</th><th>Details</th>"
            f"</tr></thead><tbody>{rows}</tbody></table></div>"
        )

    # ── recommendations ───────────────────────────────────────────────

    def _render_recs(self, recs: list[dict]) -> str:
        if not recs:
            return ""
        items = "".join(f'<li>{_esc(r.get("message", ""))}</li>' for r in recs)
        return f'<ul class="recs">{items}</ul>'


# ── Helpers ───────────────────────────────────────────────────────────

def _esc(s: str) -> str:
    return html.escape(str(s))


def _short_time(ts: str) -> str:
    """Shorten an ISO timestamp to a readable form."""
    if not ts:
        return "-"
    return ts[:16].replace("T", " ")
